name: full_fridge_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  curved_navigation_bar: ^1.0.3
  custom_navigation_bar: ^0.8.2
  email_validator: ^2.1.17
  eva_icons_flutter: ^3.1.0
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rating_stars: ^1.0.3+4
  get: ^4.6.5
  google_fonts: ^3.0.1
  lottie: ^2.0.0
  websafe_svg: ^2.1.2+7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/images/food/
    - assets/icons/illustrations/
    - assets/icons/logo/
